# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":an"
    replace: "Antoniy"

  - trigger: ";--"
    replace: "‚Äî"

  - trigger: ";.."
    replace: "‚óè"

  - trigger: ";female"
    replace: "‚ôÄÔ∏è "

  - trigger: ";male"
    replace: "‚ôÇÔ∏è "

  - trigger: ";rose"
    replace: "üåπ"

  # Inserts a markdown code block
  - trigger: ";mdc"
    replace: "```\n$|$\n```"

  - trigger: ";cite"
    replace: "‚Äî <cite>$|$</cite>"

  # Easily inputs ASCII emojis from a dropdown
  - trigger: ":lenny"
    form: "{{smileys}}"
    form_fields:
      smileys:
        type: list
        values:
        - '¬Ø\\_(„ÉÑ)_/¬Ø'
        - '( Õ°‡≤†  ñÃØ Õ°‡≤†)'
        - '‚òâ ‚Äø ‚öÜ'
        - ' ï‚Ä¢·¥•‚Ä¢ î'
        - '|·µî‚Äø·µî|'
        - '‚§ú(*Ôπè*)‚§è'
        - '„ÉÑ'

  # Kotlin
  - trigger: ";fun"
    replace: |
      fun $|$(): TYPE {
      }

  # ASC II Icons & Symbols
  - trigger: ";wtf"
    replace: "¬Ø\\_(„ÉÑ)_/¬Ø"
  
  - trigger: ";ye"
    replace: "·ïô (¬∫L¬∫,) ·ïó"
  
  - trigger: ";fuck"
    replace: "(‚ãüÔπè‚ãû)"
  
  - trigger: ";sad"
    replace: "(‚ï•_‚ï•)"
  
  - trigger: ";zen"
    replace: "‚äπ‚ï∞(‚å£ ü‚å£)‚ïØ‚äπ"

  - trigger: ":noo"
    replace: |
        N
          O
            O
             o
              o
              o
             o
            „ÄÇ
          „ÄÇ
         .
         .
          .
            .

  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"

  - trigger: ":br"
    replace: "Best Regards,\nAntoniy"

  - trigger: ";shamar"
    replace: "–ò–∑—Ö–æ–¥–∏ —Å–µ –ø–æ –≥–æ–ª—è–º–∞ –Ω—É–∂–¥–∞ –≤ —Ä—ä–∫–∞—Ç–∞ —Å–∏ –∏ —Å–∏ —É–¥–∞—Ä–∏ —à–∞–º–∞—Ä"

  # - trigger: ":greet"
  #   form: |
  #     Hey,
  #     Happy Birthday!
  #   form_fields:
  #     text:
  #       multiline: true

use_system_agent: false
